import LegalPage from "./LegalPage.jsx";
import { SITE } from "../../config/site.js";

const SECTIONS = [
  {
    id: "summary",
    heading: "The short version",
    body: (
      <>
        <p>
          {SITE.name} has no user accounts, sets no cookies, and runs no analytics or advertising
          trackers. We do not build a profile of you and we have nothing to sell about you.
        </p>
        <p>
          There is one thing you should know before using the Studio: the translation, speech
          synthesis, and voice input features send the text or audio you enter to third-party
          services in order to work. That is described in full in section 3. If you would not want
          a sentence processed by an outside provider, do not paste it into those tools.
        </p>
      </>
    ),
  },
  {
    id: "what-we-collect",
    heading: "What we collect",
    body: (
      <>
        <p>
          Directly, essentially nothing. This site is a static application. It has no sign-up, no
          login, no contact form that stores submissions, no cookies, and no analytics script. We
          do not ask for your name, email, or location to use any feature.
        </p>
        <p>
          Indirectly, our hosting provider records standard server logs when your browser requests
          a page — IP address, timestamp, requested path, user agent. These are generated by the
          host as a normal part of serving traffic and are used for delivery and abuse prevention,
          not to identify you. We do not combine them with anything else.
        </p>
        <p>
          Text you type into the Studio, and audio you record, are not stored on our servers — we do
          not have a server that could store them. They are sent to the processing services below
          and returned to your browser.
        </p>
      </>
    ),
  },
  {
    id: "third-parties",
    heading: "Third-party services that see your input",
    body: (
      <>
        <p>
          Some Studio features depend on external providers. When you use them, your input leaves
          this site. We are naming each one explicitly because a vague "we may share data with
          partners" clause would not let you make an informed choice:
        </p>
        <ul>
          <li>
            <b className="text-ink-900">Translation.</b> Text you enter for translation is sent to a
            third-party machine translation service to be translated. It is handled under that
            provider's own privacy terms, not ours.
          </li>
          <li>
            <b className="text-ink-900">Speech synthesis.</b> Text you ask us to read aloud, for
            either Nuer or Dinka, is sent to Meta's MMS models hosted on the Hugging Face Inference
            API, which returns generated audio.
          </li>
          <li>
            <b className="text-ink-900">Voice input.</b> Voice transcription uses your browser's
            built-in speech recognition. In several browsers — Chrome in particular — this uploads
            your recorded audio to the browser vendor's servers for processing. That happens between
            your browser and the vendor; we never receive the audio.
          </li>
          <li>
            <b className="text-ink-900">Hosting.</b> The site and its datasets are served by our
            hosting provider's content delivery network, which processes the request logs described
            in section 2.
          </li>
        </ul>
        <p>
          The library and dataset pages have no such dependency. Browsing or downloading the corpus
          sends nothing anywhere beyond the file request itself.
        </p>
      </>
    ),
  },
  {
    id: "contributions",
    heading: "If you contribute to the corpus",
    body: (
      <>
        <p>
          Contributing is the one place where you may deliberately give us personal information, and
          it is entirely opt-in.
        </p>
        <ul>
          <li>
            <b className="text-ink-900">Attribution.</b> Contributors are credited by name on the
            records they author or correct. If you would rather not be named, tell us and we will
            record the contribution without attribution.
          </li>
          <li>
            <b className="text-ink-900">Public by design.</b> Contributions arrive through a public
            repository. Anything you write in an issue or pull request — including the name and
            email attached to your commits — is publicly visible and outside our control to erase.
          </li>
          <li>
            <b className="text-ink-900">Voice recordings.</b> If you record pronunciation audio, that
            recording becomes part of an open dataset and may be used to train speech models. Do not
            submit a recording containing anything you would not want published permanently.
          </li>
          <li>
            <b className="text-ink-900">Email.</b> If you write to us, we keep the message in order
            to reply. We do not add you to a mailing list; there isn't one.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "children",
    heading: "Children and classroom use",
    body: (
      <p>
        The learning tools are appropriate for young learners and we expect classroom use. Because
        we collect no personal information and require no account, using the library needs no
        parental consent. Contributing does involve a public repository, so a contribution on behalf
        of a child should come from a parent, guardian, or teacher rather than the child directly.
      </p>
    ),
  },
  {
    id: "your-rights",
    heading: "Your rights",
    body: (
      <>
        <p>
          Since we hold almost nothing about you, most data requests resolve quickly: there is
          typically nothing on file to export or delete. Where we do hold something — an email you
          sent, or attribution on a contribution — you can ask us to correct or remove it.
        </p>
        <p>
          Two honest limits. Contributions published in a public repository cannot be fully
          retracted from its history or from copies others have made, so we can remove your name
          from current records but not rewrite the past. And data processed by the third parties in
          section 3 is subject to their retention policies, which we do not control.
        </p>
        <p>
          To make a request, email <a href={`mailto:${SITE.email}`}>{SITE.email}</a>.
        </p>
      </>
    ),
  },
  {
    id: "changes",
    heading: "Changes to this policy",
    body: (
      <p>
        If we add a feature that collects something new, or introduce a new third-party processor,
        we will update this page and change the date on it before the feature ships. We will not
        quietly broaden what we collect and rely on you re-reading the page to notice.
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Privacy Policy"
      title="Privacy Policy"
      lede="No accounts, no cookies, no analytics. The parts that need explaining are which third parties see what you type into the Studio — so those are named outright."
      sections={SECTIONS}
      closing={
        <p>
          Questions about anything on this page? Email{" "}
          <a
            href={`mailto:${SITE.email}`}
            className="text-ink-900 underline underline-offset-4 decoration-ink-300 hover:decoration-ink-900"
          >
            {SITE.email}
          </a>
          . See also our{" "}
          <a href="#/terms" className="text-ink-900 underline underline-offset-4 decoration-ink-300 hover:decoration-ink-900">
            Terms of Service
          </a>{" "}
          and{" "}
          <a href="#/safety" className="text-ink-900 underline underline-offset-4 decoration-ink-300 hover:decoration-ink-900">
            Safety
          </a>{" "}
          pages.
        </p>
      }
    />
  );
}
